RecycleWise/urls.py
# recyclewise/urls.py

from django.contrib import admin

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('getting_started.urls')),
    path('', include('quicktips.urls')),
    path('', include('reviews.urls')),
    path('', include('user_profile.urls')),
    path('', include('userfeedback.urls')),
    path('', include('request_services.urls')),
    path('upcoming_events/', include('upcomming_events.urls')),
    path('infographics/', include('infographics.urls')),
    path('interactivetools/', include('interactivetools.urls')),
    path('community_engagement/', include('community_engagement.urls')),
    path('recycling_guides/', include('recycling_guides.urls')),
    path('userhistory/', include('userhistory.urls')),
    path('featured_videos/', include('featured_videos.urls')),
    path('aboutus/', include('aboutus.urls')),


    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutus/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('team/', views.team_member_list, name='team_member_list'),
    path('team/<int:pk>/', views.team_member_detail, name='team_member_detail'),
    path('team/add/', views.add_team_member, name='add_team_member'),
    path('team/<int:pk>/edit/', views.edit_team_member, name='edit_team_member'),
    path('sections/', views.section_list, name='section_list'),
    path('sections/<int:pk>/', views.section_detail, name='section_detail'),
    path('sections/add/', views.add_section, name='add_section'),
]

quicktips/urls.py
from django.urls import path, include
from quicktips import views

app_name = 'quicktips'

urlpatterns = [
    path('quicktips/', views.quicktips_view, name='quicktips_view'),
    path('quicktips/add/', views.add_tip_view, name='add_tip'),
]

quicktips/models.py
from django.db import models



# Create your models here.
class WasteType(models.Model):
    Waste_Options = [
        ('BW', 'Bulky Waste'),
        ('GW', 'General Waste'),
        ('HW', 'Hazardous Waste'),
        ('OW', 'Organic Waste'),
        ('RW', 'Recyclable Waste'),
        ('SW', 'Select your Waste')
    ]
    waste_choices = models.CharField(max_length=2, choices=Waste_Options, default='SW')

    def __str__(self):
        return self.waste_choices


class Tip(models.Model):
    waste_type = models.ForeignKey(WasteType, related_name='Tips', on_delete=models.CASCADE)
    description = models.TextField(max_length=500)

    # image = models.ImageField(upload_to='Waste-Images/', null=True, blank=True)

    def __str__(self):
        return f"{self.description}"

quicktips/forms.py
from django import forms
from .models import Tip, WasteType

class WasteTypeForm(forms.ModelForm):
    class Meta:
        model = WasteType
        fields = ['waste_choices']

class TipForm(forms.ModelForm):
    class Meta:
        model = Tip
        fields = ['waste_type', 'description']
        widgets = {
            'waste_type': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

quicktips/views.py
from django.shortcuts import render, redirect
from .forms import WasteTypeForm, TipForm
from .models import WasteType, Tip

def quicktips_view(request):
    form = WasteTypeForm(request.GET)
    tips = None
    waste_choice_display = None

    if form.is_valid():
        waste_choice_key = form.cleaned_data['waste_choices']
        tips = Tip.objects.filter(waste_type__waste_choices=waste_choice_key)
        waste_choice_display = dict(WasteType.Waste_Options).get(waste_choice_key)

    return render(request, 'quicktips/get_recycletips.html', {
        'tips': tips,
        'form': form,
        'waste_choice_display': waste_choice_display
    })

def add_tip_view(request):
    if request.method == 'POST':
        form = TipForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'quicktips/thank_you.html')
    else:
        form = TipForm()

    return render(request, 'quicktips/add_tip.html', {'form': form})

templates/quicktips/add_tip.html
{% extends "base.html" %}

{% block title %}
    Add Tip
{% endblock %}

{% block content %}
<div class="container py-4 wow animate__animated animate__slideInLeft" data-wow-duration="1s">
    <h1>Add a New Tip</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-light-green mb-4">Submit</button>
    </form>
</div>
    <style>
    .btn-light-green {
        background-color: #2dbb2d;
        color: white;
    }
    .btn-light-green:hover {
        background-color: #0da60d;
        color: white;
    }
    </style>
    
{% endblock %}

templates/quicktips/get_recycletips.html
{% extends "base.html" %}

{% block title %}
    Quick Tips
{% endblock %}

{% block content %}
<div class="container py-4 wow animate__animated animate__slideInLeft" data-wow-duration="1s">
    <h1>Get Recycling Tips</h1>
    <form method="get" class="mb-4">
        {{ form.as_p }}
        <input type="submit" class="btn btn-light-green btn-block w-50" value="Get Tips">
    </form>
    <a href="{% url 'quicktips:add_tip' %}" class="btn btn-light-green2 btn-block w-50 mb-4">Add a New Tip</a>

    {% if waste_choice_display %}
        <h2 class="mt-4">Tips for {{ waste_choice_display }}</h2>
        <ul class="list-group">
            {% if tips %}
                {% for tip in tips %}
                    <li class="list-group-item">{{ tip.description }}</li>
                {% endfor %}
            {% else %}
                <li class="list-group-item">No tips available for this waste type.</li>
            {% endif %}
        </ul>
    {% endif %}
</div>
    
        <style>
    .btn-light-green {
        background-color: #2dbb2d;
        color: white;
    }
    .btn-light-green:hover {
        background-color: #0da60d;
        color: white;
    }
    
    .btn-light-green2 {
        background-color: #186718;
        color: white;
    }
    .btn-light-green2:hover {
        background-color: #053805;
        color: white;
    }
</style>
{% endblock %}

templates/quicktips/thank_you.html
{% extends "base.html" %}

{% block title %}
    Thank You
{% endblock %}

{% block content %}
<div class="container py-4 wow animate__animated animate__zoomIn" data-wow-duration="2s">
    <h1>Thank you for adding to our success</h1>
    <p>Your tip has been successfully added.</p>
    <a href="{% url 'quicktips:quicktips_view' %}" class="btn btn-light-green mb-4">Back to Tips</a>
</div>
    
    <style>
    .btn-light-green {
        background-color: #2dbb2d;
        color: white;
    }
    .btn-light-green:hover {
        background-color: #0da60d;
        color: white;
    }
    </style>
{% endblock %}